"""The P1-P5 patch-back mechanism ladder: always take the highest rung that works,
and verify with a dispatch assertion (new kernel present in the re-profiled trace AND
the old one absent). Design rationale: docs/DESIGN.md."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from pydantic import Field

from xe_forge.orbit.models import Artifact, KernelRecord, PatchPoint


class PatchError(RuntimeError):
    """Raised when a patch cannot be applied, or cannot be proven to have applied."""


# Ordered best-first; `apply` takes the first rung available and supported.
RUNG_ORDER = ("P1", "P2", "P3", "P4", "P5")

_RUNG_DESCRIPTION = {
    "P1": "operator override through the PyTorch dispatcher",
    "P2": "custom op + Inductor post-grad pattern replacement",
    "P3": "framework registry substitution",
    "P4": "import-time module shim",
    "P5": "source patch and rebuild",
}

_RUNG_TOUCHES = {
    "P1": "nothing in the framework",
    "P2": "the compile pipeline only",
    "P3": "framework configuration",
    "P4": "process state",
    "P5": "the source tree and its build",
}


class AppliedPatch(Artifact):
    """The record every applied patch leaves behind: rung, target symbol, the
    registration call, the revert procedure and the verification result."""

    kernel_id: str
    rung: str
    target: str
    mechanism: str = ""
    module_path: str | None = None
    registration_call: str = ""
    revert_procedure: str = ""
    applied: bool = False
    verified: bool = False
    verification_detail: str = ""
    worktree: str | None = None
    env_overrides: dict[str, str] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)


@dataclass
class DispatchAssertion:
    """Outcome of re-profiling after a patch. `new_kernel_present` alone is not
    enough: a workload running both the old and new kernel has not been patched."""

    new_kernel_present: bool = False
    old_kernel_absent: bool = False
    observed_kernels: list[str] = field(default_factory=list)
    detail: str = ""

    @property
    def took_effect(self) -> bool:
        return self.new_kernel_present and self.old_kernel_absent


def available_rungs(kernel: KernelRecord, patch_points: list[PatchPoint]) -> list[PatchPoint]:
    """Patch points for this kernel, ordered highest rung first."""
    ordered = sorted(
        patch_points,
        key=lambda p: RUNG_ORDER.index(p.rung) if p.rung in RUNG_ORDER else len(RUNG_ORDER),
    )
    return ordered


def choose_rung(kernel: KernelRecord, patch_points: list[PatchPoint]) -> PatchPoint:
    """Pick the highest rung that applies, or explain why none does."""
    ordered = available_rungs(kernel, patch_points)
    if not ordered:
        raise PatchError(
            f"no patch point available for {kernel.id} ({kernel.runtime_name}). "
            f"Provider {kernel.provider.value} with no registered op cannot be reached "
            f"by operator override; for an opaque library primitive the action is a "
            f"backend or config change, not source replacement."
        )
    return ordered[0]


def render_operator_override(
    kernel: KernelRecord,
    op_name: str,
    implementation_module: str,
    device_key: str = "XPU",
) -> str:
    """Generate the P1 override module.

    The output is a small importable module that registers an implementation for an
    existing op on the device key, shadowing the default. Nothing in the framework is
    modified; reverting is not importing this module.
    """
    namespace, _, op = op_name.partition("::")
    if not op:
        namespace, op = "aten", op_name

    return f'''"""
Operator override for {op_name} (rung P1).

Generated by xe-orbit. Registers an alternative implementation for an existing
dispatcher op on the {device_key} key, shadowing the default. Nothing in the
framework is modified.

To apply:   import this module before the first call to the op.
To revert:  do not import it.

Registration must happen before the op is first dispatched, and before any
`torch.compile` graph containing it is captured, or the override silently does not
take effect — which is why the dispatch assertion is mandatory.
"""

import torch

from {implementation_module} import optimized_kernel

_LIBRARY = torch.library.Library({namespace!r}, "IMPL")


def _dispatch(*args, **kwargs):
    return optimized_kernel(*args, **kwargs)


_LIBRARY.impl({op!r}, _dispatch, {device_key!r})

REGISTRATION = "torch.library.Library({namespace!r}, 'IMPL').impl({op!r}, ..., {device_key!r})"
TARGET_OP = {op_name!r}
'''


def _is_native(kernel: KernelRecord) -> bool:
    """True when the override must be compiled rather than imported."""
    language = getattr(kernel.language, "value", None)
    return language in ("sycl", "sycl_tla", "cpp")


def apply_patch(
    kernel: KernelRecord,
    patch_points: list[PatchPoint],
    candidate_module: str,
    output_dir: Path,
    worktree: Path | None = None,
    device_name: str | None = None,
    build_native: bool = True,
) -> AppliedPatch:
    """Apply the highest available rung and write the patch record.

    This writes the override module; it does not import it. Applying a patch into the
    measuring process would contaminate the baseline, so the module is written here and
    imported by the workload under test.
    """
    point = choose_rung(kernel, patch_points)
    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)

    record = AppliedPatch(
        kernel_id=kernel.id,
        rung=point.rung,
        target=point.target,
        mechanism=point.mechanism or _RUNG_DESCRIPTION.get(point.rung, ""),
        worktree=str(worktree) if worktree else None,
    )

    if point.rung == "P1" and _is_native(kernel):
        # Native ops reach the dispatcher the same way; the override just has to be
        # compiled first.
        from xe_forge.orbit.patch.sycl_override import generate

        artifacts = generate(
            kernel,
            point.target,
            target,
            device_name=device_name,
            build=build_native,
        )
        record.module_path = str(artifacts.loader_path)
        record.registration_call = (
            f"TORCH_LIBRARY_IMPL({point.target.split('::')[0]}, XPU, m) "
            f'{{ m.impl("{point.target.split("::")[-1]}", ...); }}'
        )
        record.revert_procedure = (
            f"do not import {artifacts.loader_path.name}; the extension is inert unless "
            f"torch.ops.load_library is called. No framework source was modified."
        )
        record.env_overrides = {"PYTHONPATH": str(target)}
        record.applied = artifacts.built
        record.notes.append(
            f"P1 for a native op: out-of-tree extension compiled with "
            f"{artifacts.build.compiler}, no fork of PyTorch, vLLM or SGLang."
        )
        if not artifacts.built:
            record.notes.append(f"not compiled: {artifacts.reason}")
        if artifacts.build.aot_target:
            record.notes.append(f"AOT target pinned to {artifacts.build.aot_target}")
        return record

    if point.rung == "P1":
        module_source = render_operator_override(kernel, point.target, candidate_module)
        module_path = target / f"orbit_override_{kernel.id}.py"
        module_path.write_text(module_source, encoding="utf-8")
        record.module_path = str(module_path)
        record.registration_call = f"torch.library.Library(...).impl({point.target!r}, ...)"
        record.revert_procedure = (
            f"do not import {module_path.name}; no framework state was modified"
        )
        record.env_overrides = {"PYTHONPATH": str(target)}
        record.applied = True
        record.notes.append(
            f"P1 touches {_RUNG_TOUCHES['P1']}. The same override ports to any framework "
            f"that dispatches through {point.target}."
        )
        return record

    # Rungs below P1 modify something and are described, never auto-applied.
    record.applied = False
    record.revert_procedure = "n/a — not applied"
    record.notes.append(
        f"rung {point.rung} ({_RUNG_DESCRIPTION.get(point.rung, 'unknown')}) touches "
        f"{_RUNG_TOUCHES.get(point.rung, 'unknown state')} and is not applied "
        f"automatically. Apply it deliberately and record the change."
    )
    return record


def assert_dispatch(
    observed_kernels: list[str],
    original_kernel: str,
    replacement_marker: str,
) -> DispatchAssertion:
    """Confirm the patch actually took effect: the new kernel must appear in the
    re-profiled trace AND the old one must be gone."""
    normalized = [k.lower() for k in observed_kernels]
    new_present = any(replacement_marker.lower() in k for k in normalized)
    old_absent = not any(original_kernel.lower() in k for k in normalized)

    assertion = DispatchAssertion(
        new_kernel_present=new_present,
        old_kernel_absent=old_absent,
        observed_kernels=list(observed_kernels),
    )

    if assertion.took_effect:
        assertion.detail = (
            f"{replacement_marker!r} present and {original_kernel!r} absent: the override "
            f"is what executes"
        )
    elif new_present and not old_absent:
        assertion.detail = (
            f"both {replacement_marker!r} and {original_kernel!r} appear in the trace: the "
            f"override did not replace the original, it was added alongside it"
        )
    elif not new_present:
        assertion.detail = (
            f"{replacement_marker!r} never appears: the override did not take effect. "
            f"Common causes are the wrong dispatch key, the wrong overload, registration "
            f"after the first call, or a torch.compile graph captured before registration. "
            f"This would otherwise look like an honest 'no change' result."
        )
    else:
        assertion.detail = "inconclusive"

    return assertion


def revert_patch(record: AppliedPatch) -> bool:
    """Undo an applied patch. Returns whether anything needed undoing."""
    if not record.applied:
        return False
    if record.rung == "P1" and record.module_path:
        # The module is inert unless imported; removing it is housekeeping.
        path = Path(record.module_path)
        if path.is_file():
            path.unlink()
        record.applied = False
        return True
    raise PatchError(
        f"rung {record.rung} has no automatic revert; follow the recorded procedure: "
        f"{record.revert_procedure}"
    )


# ---------------------------------------------------------------------------
# Candidate isolation
# ---------------------------------------------------------------------------


def create_worktree(repo: Path, branch: str, destination: Path) -> Path:
    """Put a candidate in its own git worktree, never the working tree."""
    destination = Path(destination)
    result = subprocess.run(
        ["git", "worktree", "add", "-b", branch, str(destination)],
        cwd=str(repo),
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if result.returncode != 0:
        raise PatchError(f"could not create worktree at {destination}: {result.stderr.strip()}")
    return destination


def remove_worktree(repo: Path, destination: Path) -> bool:
    """Remove a candidate worktree, leaving the main tree untouched."""
    result = subprocess.run(
        ["git", "worktree", "remove", "--force", str(destination)],
        cwd=str(repo),
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    return result.returncode == 0
