"""
Operator override for SYCL kernels (plan §11.8, §13 rung P1).

This is the part that makes SYCL support practical rather than theoretical. Because
`torch-xpu-ops`, IPEX, vLLM-XPU and `sgl-kernel-xpu` all register their kernels as
dispatcher ops, an optimized SYCL kernel ships as a **small out-of-tree extension**,
compiled with icpx, that registers an implementation on the XPU key and shadows the
original.

No fork of PyTorch. No fork of vLLM or SGLang. No patched build of `libtorch_xpu`.
Reverting is not loading the shared object.

P5 — patching the source tree and rebuilding — is reserved for kernels that are *not*
dispatch-registered, and it is the rung to avoid: it drags the framework's entire build
into the loop and binds the artifact to one source revision.

The mechanism differs from the Triton path in exactly one way: the override has to be
compiled before it can be registered. Everything after that — the dispatch assertion,
the revert, the version binding — is identical, which is the point of treating language
as a dimension rather than a special case (§11.3).
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from xe_forge.orbit.models import BuildRecipe, KernelRecord

# icpx is the Intel oneAPI DPC++ compiler; dpcpp is its older name. A stock clang++ is
# deliberately NOT in this list: it accepts `-fsycl` only in builds with the SYCL
# runtime enabled, so falling back to it turns "oneAPI is not installed" into a compiler
# error with an exit code, which is a worse answer to the same question.
SYCL_COMPILERS = ("icpx", "dpcpp")

# Flags every SYCL override needs. AOT target flags are added per device by the caller,
# because a bundle that AOT-builds a kernel the workload JITs is not the same kernel
# (§11.4).
BASE_FLAGS = ("-fsycl", "-fPIC", "-shared", "-std=c++17", "-O3")


@dataclass
class SyclOverrideArtifacts:
    """Everything needed to build, load and revert a SYCL operator override."""

    source_path: Path
    loader_path: Path
    build: BuildRecipe
    op_name: str
    library_path: Path | None = None
    build_log: str = ""
    built: bool = False
    reason: str = ""
    notes: list[str] = field(default_factory=list)


# oneAPI is routinely installed without being on PATH: the toolkit expects you to
# source `setvars.sh` first, and a distro package drops the compiler under /opt. Looking
# only at PATH would report "no SYCL compiler" on a machine that has one installed,
# which is a wrong answer to the question the caller actually asked.
ONEAPI_SEARCH_ROOTS = (
    "/opt/intel/oneapi/compiler/latest/bin",
    "/opt/intel/oneapi/compiler/latest/linux/bin",
    "/usr/lib/intel/oneapi/compiler/latest/bin",
)


def available_compiler() -> str | None:
    """The SYCL compiler, from PATH or a standard oneAPI install location.

    Its absence is not a design failure — identity, closure, the option axes and the
    generated source all work without it. Only the build step needs oneAPI installed.

    Returns an absolute path when the compiler was found off-PATH, so the recorded
    compile line reproduces without the caller having sourced `setvars.sh` (§11.5 wants
    the command verbatim, and a bare `icpx` is not verbatim if it only resolves inside
    a sourced shell).
    """
    for candidate in SYCL_COMPILERS:
        found = shutil.which(candidate)
        if found:
            return found

    for root in ONEAPI_SEARCH_ROOTS:
        for candidate in SYCL_COMPILERS:
            path = Path(root) / candidate
            if path.is_file():
                return str(path)
    return None


def render_override_source(
    kernel: KernelRecord,
    op_name: str,
    kernel_body: str | None = None,
    device_key: str = "XPU",
) -> str:
    """Generate the out-of-tree extension that shadows the original op.

    `TORCH_LIBRARY_IMPL(ns, XPU, m)` is the C++ equivalent of the Python
    `torch.library.Library(ns, "IMPL").impl(op, fn, "XPU")` the Triton path uses. The
    dispatcher does not care which language registered the implementation, which is
    precisely why P1 ports across languages for free.
    """
    namespace, _, op = op_name.partition("::")
    if not op:
        namespace, op = "aten", op_name

    body = kernel_body or _default_kernel_body()

    return f"""// Operator override for {op_name} (plan §11.8, rung P1).
//
// Generated by xe-orbit. Compiled as an out-of-tree extension with icpx and loaded via
// torch.ops.load_library, this registers an implementation for an op that already
// exists on the {device_key} dispatch key, shadowing the original.
//
// Nothing in PyTorch, vLLM or SGLang is modified. Reverting is not loading this
// shared object.
//
// The registration happens at library load, so the library must be loaded before the
// op is first dispatched — and before any torch.compile graph containing it is
// captured. A graph captured earlier has already specialized on the original, and the
// override will silently not take effect: the failure mode that looks exactly like an
// honest "no change" result, which is why §13 makes the dispatch assertion mandatory.

// Deliberately NOT <torch/extension.h>: that header pulls in pybind11 and Python.h to
// build a Python *module*. An operator override is not a module — it is loaded with
// torch.ops.load_library and registers itself through the dispatcher, so requiring the
// Python development headers would add a build dependency the artifact never uses.
#include <torch/library.h>
#include <sycl/sycl.hpp>

#include <ATen/ATen.h>
#include <c10/xpu/XPUStream.h>

namespace orbit_override {{

// The optimized kernel. Xe-Forge produces this body; the scaffolding around it is
// what Orbit contributes.
{body}

}}  // namespace orbit_override

// Shadowing registration. TORCH_LIBRARY_IMPL binds to an existing schema rather than
// defining a new one, which is what makes this an override and not a second op.
TORCH_LIBRARY_IMPL({namespace}, {device_key}, m) {{
  m.impl("{op}", TORCH_FN(orbit_override::orbit_kernel));
}}
"""


# Two failures that cost real debugging on the first live SYCL override, both worth
# stating because neither is discoverable from the generated source:
#
# 1. **The C++ signature must match the registered schema exactly**, including by-value
#    versus by-const-reference. Registering `const std::optional<at::Tensor>&` against a
#    schema declaring `std::optional<at::Tensor>` aborts the process at load with
#    "Mismatch in kernel C++ signatures". That is the good outcome — the dispatcher
#    refuses rather than accepting a registration that would never shadow — but it is
#    fatal rather than diagnosable, so the signature is worth deriving from the schema
#    rather than written by hand.
#
# 2. **Use `sycl::reduce_over_group`, not a hand-rolled barrier tree.** A tree reduction
#    with a barrier per level hung the device outright: every work-item must reach every
#    barrier, and getting that subtly wrong on Xe does not fault, it stops, and the
#    process has to be killed. The library primitive is also what the compiler can map
#    onto sub-group hardware reductions.
SIGNATURE_MUST_MATCH_SCHEMA = (
    "the override's C++ signature must match the registered schema exactly, including "
    "by-value versus by-const-reference; a mismatch aborts at load"
)
PREFER_GROUP_REDUCTION = (
    "use sycl::reduce_over_group rather than a hand-rolled barrier tree; a missed "
    "barrier on Xe hangs the device rather than faulting"
)


def _default_kernel_body() -> str:
    """A compilable identity kernel, so the scaffolding can be validated on its own.

    Emitting a stub that fails to compile would make it impossible to tell a broken
    generator from a broken candidate.
    """
    return """at::Tensor orbit_kernel(const at::Tensor& input) {
  // Placeholder: Xe-Forge replaces this body with the optimized kernel.
  // Kept compilable on purpose — a stub that does not build makes a generator bug
  // indistinguishable from a candidate bug.
  auto output = at::empty_like(input);
  auto queue = c10::xpu::getCurrentXPUStream().queue();

  const auto* in_ptr = input.data_ptr<float>();
  auto* out_ptr = output.data_ptr<float>();
  const auto count = input.numel();

  queue.parallel_for(sycl::range<1>(count), [=](sycl::id<1> idx) {
    out_ptr[idx] = in_ptr[idx];
  });
  queue.wait();
  return output;
}"""


def render_loader(library_path: Path, op_name: str) -> str:
    """The Python shim that loads the compiled extension.

    Loading is what applies the patch, so this module is the SYCL analogue of the
    Triton override module: importing it registers, not importing it reverts.
    """
    return f'''"""
Loader for the compiled SYCL operator override of {op_name} (plan §11.8).

Importing this module loads the extension, which registers the override on the XPU
dispatch key. Not importing it is the revert — nothing in the framework was modified.
"""

import torch

LIBRARY_PATH = {str(library_path)!r}
TARGET_OP = {op_name!r}

torch.ops.load_library(LIBRARY_PATH)
'''


def build_recipe_for(
    kernel: KernelRecord,
    source_path: Path,
    device_name: str | None = None,
    extra_flags: tuple[str, ...] = (),
) -> BuildRecipe:
    """Compose the compile line, pinning the AOT target when the device is known."""
    from xe_forge.orbit.languages.sycl_backend import aot_target_for_device

    flags = list(BASE_FLAGS) + list(extra_flags)
    aot_target = aot_target_for_device(device_name or "") if device_name else None
    if aot_target:
        # AOT and JIT do not perform the same and do not rebuild the same, so the
        # target is recorded rather than left to whatever the runtime picks (§11.4).
        flags += ["-fsycl-targets=spir64_gen", "-Xs", f"-device {aot_target}"]

    return BuildRecipe(
        compiler=available_compiler() or "icpx",
        flags=flags,
        includes=_torch_include_dirs(),
        link=_torch_link_flags(),
        entry_symbol="orbit_kernel",
        aot_target=aot_target,
    )


def _torch_include_dirs() -> list[str]:
    """Torch's C++ headers, resolved from the installed package rather than guessed."""
    try:
        from torch.utils import cpp_extension

        return list(cpp_extension.include_paths())
    except Exception:
        return []


def _torch_link_flags() -> list[str]:
    try:
        from torch.utils import cpp_extension

        libs = [f"-L{path}" for path in cpp_extension.library_paths()]
        return [*libs, "-ltorch", "-ltorch_cpu", "-lc10"]
    except Exception:
        return []


def generate(
    kernel: KernelRecord,
    op_name: str,
    output_dir: Path,
    *,
    kernel_body: str | None = None,
    device_name: str | None = None,
    build: bool = True,
) -> SyclOverrideArtifacts:
    """Write the override source, its loader and its build recipe; optionally compile.

    Generation always succeeds and is fully testable without oneAPI. Only the build
    step needs a compiler, and its absence is reported rather than raised — the
    artifacts are still useful for review, for a build on a machine that has icpx, and
    for the option-axis sweep (§11.7).
    """
    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)

    source_path = target / f"orbit_override_{kernel.id}.cpp"
    source_path.write_text(render_override_source(kernel, op_name, kernel_body), encoding="utf-8")

    library_path = target / f"liborbit_override_{kernel.id}.so"
    recipe = build_recipe_for(kernel, source_path, device_name=device_name)

    loader_path = target / f"orbit_override_{kernel.id}.py"
    loader_path.write_text(render_loader(library_path, op_name), encoding="utf-8")

    artifacts = SyclOverrideArtifacts(
        source_path=source_path,
        loader_path=loader_path,
        build=recipe,
        op_name=op_name,
    )

    compiler = available_compiler()
    if not build:
        artifacts.reason = "build not requested"
        return artifacts
    if compiler is None:
        artifacts.reason = (
            f"no SYCL compiler on PATH (looked for {', '.join(SYCL_COMPILERS)}). "
            f"Source, loader and build recipe were generated; install oneAPI to compile. "
            f"Identity, closure and the compiler-option axes do not need it."
        )
        artifacts.notes.append(f"compile line: {' '.join(compile_command(artifacts))}")
        return artifacts

    result = _compile(artifacts, library_path)
    artifacts.built = result.returncode == 0
    artifacts.build_log = (result.stdout + result.stderr)[-4000:]
    if artifacts.built:
        artifacts.library_path = library_path
    else:
        artifacts.reason = f"{compiler} exited {result.returncode}"
    return artifacts


def compile_command(artifacts: SyclOverrideArtifacts) -> list[str]:
    """The exact command that builds this override, recorded verbatim (§11.5)."""
    recipe = artifacts.build
    argv = [recipe.compiler, *recipe.flags, str(artifacts.source_path)]
    argv += [f"-I{path}" for path in recipe.includes]
    argv += [f"-D{key}={value}" if value else f"-D{key}" for key, value in recipe.defines.items()]
    argv += list(recipe.link)
    argv += ["-o", str(artifacts.source_path.with_name(f"lib{artifacts.source_path.stem}.so"))]
    return argv


def _compile(artifacts: SyclOverrideArtifacts, library_path: Path):
    argv = compile_command(artifacts)
    argv[-1] = str(library_path)
    return subprocess.run(argv, capture_output=True, text=True, timeout=1800, check=False)
