"""Correctness harness for an in-place kernel, rendered as a standalone script and run
in a fresh process so the file on disk is what gets checked. Exit codes: 0 correct,
1 wrong, 2 could not be checked — 2 never collapses into the others.
Design rationale: docs/DESIGN.md."""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path

# A correctness check is a handful of kernel launches; beyond this something is hung.
DEFAULT_TIMEOUT_S = 600.0

# Below this fraction of rows matching, the kernel is wrong.
DEFAULT_PASS_FRACTION = 0.999


# For paths no torch reference can reproduce (e.g. Triton's Philox RNG stream), the
# check is differential: pre-patch vs post-patch with identical seeds and inputs.
DIFFERENTIAL_NOTE = (
    "differential: same seed, same inputs, output must be bit-identical to the pre-patch kernel"
)


class CheckOutcome(StrEnum):
    CORRECT = "correct"
    WRONG = "wrong"
    # Distinct from WRONG on purpose: nothing was established about the kernel.
    UNCHECKED = "unchecked"


@dataclass
class CheckResult:
    outcome: CheckOutcome
    accuracy: float | None = None
    detail: str = ""

    @property
    def correct(self) -> bool:
        return self.outcome is CheckOutcome.CORRECT

    def format(self) -> str:
        if self.accuracy is None:
            return f"[{self.outcome.value}] {self.detail}"
        return f"[{self.outcome.value}] accuracy {self.accuracy:.4f} — {self.detail}"


# Shapes a correctness check must span; the largest is chosen to stress int32 index
# width, not to be representative.
DEFAULT_SHAPE_SWEEP = (256, 4096, 16384)


@dataclass
class HarnessSpec:
    """What it takes to check one kernel against a reference.

    `reference_expr` must be independent of the kernel under test and computed in
    higher precision.
    """

    kernel_id: str
    import_statement: str
    setup: str
    call_expr: str
    reference_expr: str
    comparison: str = "exact"
    notes: str = ""
    # Values substituted for `{n}` in `setup`, one run each.
    shapes: tuple[int, ...] = DEFAULT_SHAPE_SWEEP


def render_harness(spec: HarnessSpec) -> str:
    """Render a standalone correctness script for one kernel."""
    compare_block = (
        "    match = (actual.to(torch.int64) == reference.to(torch.int64))\n"
        "    correct = int(match.sum().item()); total = int(match.numel())\n"
        if spec.comparison == "exact"
        else (
            "    from xe_forge.orbit.compare.accuracy import compare_tensors\n"
            "    result = compare_tensors(actual, reference)\n"
            "    correct, total = result.correct, result.total\n"
        )
    )
    return f'''"""Correctness check for {spec.kernel_id}, generated by Xe-Orbit.

The kernel is imported from the installed tree exactly as the workload imports it;
the reference is independent and computed in higher precision.

{spec.notes}
"""
import json, sys
from pathlib import Path


def main() -> int:
    import torch
    if not (hasattr(torch, "xpu") and torch.xpu.is_available()):
        print("UNCHECKED: no XPU device", file=sys.stderr)
        return 2

    try:
        {spec.import_statement}
    except Exception as exc:
        # An import failure says nothing about the kernel's numerics.
        print(f"UNCHECKED: import failed: {{exc}}", file=sys.stderr)
        return 2

    torch.manual_seed(0)
{_indent(spec.setup, 4)}

    try:
        actual = {spec.call_expr}
        reference = {spec.reference_expr}
    except Exception as exc:
        print(f"UNCHECKED: kernel or reference raised: {{exc}}", file=sys.stderr)
        return 2

{compare_block}
    accuracy = correct / total if total else 0.0
    Path("accuracy.json").write_text(json.dumps(
        {{"accuracy": accuracy, "correct": correct, "total": total,
          "kernel_id": "{spec.kernel_id}"}}, indent=2))
    print(f"ACCURACY {{accuracy:.6f}} {{correct}}/{{total}}")
    return 0 if accuracy >= {DEFAULT_PASS_FRACTION} else 1


if __name__ == "__main__":
    sys.exit(main())
'''


def run_harness(
    script: Path,
    python: str | None = None,
    cwd: Path | None = None,
    timeout_s: float = DEFAULT_TIMEOUT_S,
) -> CheckResult:
    """Run a rendered harness in a fresh process and read its verdict.

    A fresh process is required: a module imported earlier in this interpreter would
    keep serving the pre-patch source.
    """
    try:
        completed = subprocess.run(
            [python or sys.executable, str(script)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=str(cwd) if cwd else None,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return CheckResult(
            CheckOutcome.UNCHECKED,
            detail=f"harness did not finish within {timeout_s:.0f}s",
        )
    except OSError as exc:
        return CheckResult(CheckOutcome.UNCHECKED, detail=f"could not run harness: {exc}")

    accuracy = _parse_accuracy(completed.stdout)

    if completed.returncode == 2:
        return CheckResult(
            CheckOutcome.UNCHECKED,
            accuracy=accuracy,
            detail=_last_line(completed.stderr) or "harness reported it could not check",
        )
    if completed.returncode == 0:
        return CheckResult(CheckOutcome.CORRECT, accuracy=accuracy, detail="matches the reference")
    if completed.returncode == 1:
        # Exit 1 is ambiguous: an uncaught exception produces it too. Without an
        # ACCURACY line this is a crash, not a failing kernel.
        if accuracy is None:
            return CheckResult(
                CheckOutcome.UNCHECKED,
                detail=f"harness crashed before reporting: {_last_line(completed.stderr)}",
            )
        return CheckResult(
            CheckOutcome.WRONG,
            accuracy=accuracy,
            detail="output does not match the reference",
        )
    # A code the harness does not define — a crash, a signal. Not a numerical verdict.
    return CheckResult(
        CheckOutcome.UNCHECKED,
        accuracy=accuracy,
        detail=f"harness exited {completed.returncode}: {_last_line(completed.stderr)}",
    )


def _parse_accuracy(stdout: str) -> float | None:
    for line in stdout.splitlines():
        if line.startswith("ACCURACY "):
            try:
                return float(line.split()[1])
            except (IndexError, ValueError):
                return None
    return None


def _last_line(text: str) -> str:
    lines = [line for line in (text or "").strip().splitlines() if line.strip()]
    return lines[-1][:200] if lines else ""


def _indent(block: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in block.splitlines())


@dataclass
class DifferentialSpec:
    """Check a patched kernel against the pre-patch kernel, not against a reference.

    Used where no independent reference can reach a path: identical seeds must yield
    bit-identical output. Proves behaviour preservation, not correctness.
    """

    kernel_id: str
    import_statement: str
    setup: str
    call_expr: str
    # Each case names one execution path; span the branches a reference cannot.
    cases: list[dict[str, object]] = field(default_factory=list)
    notes: str = ""


def render_differential(spec: DifferentialSpec) -> str:
    """Render a save/compare harness: snapshot before the patch, verify after."""
    cases = json.dumps(spec.cases or [{}], indent=8)
    return f'''"""Differential check for {spec.kernel_id}, generated by Xe-Orbit.

Run with --save before patching and --compare after. Identical seeds mean identical RNG
streams, so any difference is the patch. This reaches paths a torch reference cannot —
which is the point: {spec.notes}
"""
import argparse, json, sys
from pathlib import Path

CASES = {cases}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--save"); ap.add_argument("--compare")
    args = ap.parse_args()

    import torch
    if not (hasattr(torch, "xpu") and torch.xpu.is_available()):
        print("UNCHECKED: no XPU device", file=sys.stderr); return 2
    try:
        {spec.import_statement}
    except Exception as exc:
        print(f"UNCHECKED: import failed: {{exc}}", file=sys.stderr); return 2

    results = []
    for case in CASES:
        torch.manual_seed(0)          # same stream on both sides of the patch
{_indent(spec.setup, 8)}
        try:
            out = {spec.call_expr}
        except Exception as exc:
            print(f"UNCHECKED: case {{case}} raised: {{exc}}", file=sys.stderr); return 2
        results.append(out.detach().to("cpu").tolist())

    if args.save:
        Path(args.save).write_text(json.dumps(results))
        print(f"SAVED {{len(results)}} cases"); return 0

    if not args.compare:
        print("UNCHECKED: neither --save nor --compare given", file=sys.stderr); return 2
    try:
        expected = json.loads(Path(args.compare).read_text())
    except Exception as exc:
        print(f"UNCHECKED: no baseline to compare against: {{exc}}", file=sys.stderr); return 2

    if len(expected) != len(results):
        print("UNCHECKED: case count changed between runs", file=sys.stderr); return 2

    matched = sum(1 for a, b in zip(expected, results) if a == b)
    total = len(results)
    print(f"ACCURACY {{matched / total:.6f}} {{matched}}/{{total}}")
    return 0 if matched == total else 1


if __name__ == "__main__":
    sys.exit(main())
'''


def combined_check(checks: list[CheckResult]) -> CheckResult:
    """Require every check to pass and report the weakest outcome: any WRONG wins,
    then any UNCHECKED, else CORRECT with the minimum accuracy."""
    if not checks:
        return CheckResult(CheckOutcome.UNCHECKED, detail="no checks were run")

    for result in checks:
        if result.outcome is CheckOutcome.WRONG:
            return result
    for result in checks:
        if result.outcome is CheckOutcome.UNCHECKED:
            return result

    accuracies = [c.accuracy for c in checks if c.accuracy is not None]
    return CheckResult(
        CheckOutcome.CORRECT,
        accuracy=min(accuracies) if accuracies else None,
        detail=f"all {len(checks)} checks passed, including paths no reference reaches",
    )
