"""Finalize a standalone ``.visaasm`` kernel into an executable Xe2 binary.

There is no standalone vISA assembler in the driver stack, so finalization goes
through IGC itself via its ``ShaderOverride`` mechanism, applied to an **ABI stub**:

1. :func:`stub_source` writes a Triton kernel with the target's exact signature
   and an inert body. Its SPIR-V is compiled by Triton (in the GPU child, see
   :mod:`xe_forge.lowering.visa.runner`). The stub contains none of the target's
   computation, so nothing IGC produces for it can leak the lowering.
2. **Pass 1** (:meth:`VisaCompiler.discover_abi`) compiles the stub with shader
   dumps on, into a sealed directory outside any workspace. Exactly three facts
   are taken from it: the dump file name (the override key), the ``.ze_info``
   payload layout, and the stub's ``.input``/``.kernel_attr`` lines, which are
   used only to cross-check the layout. The dump text is then given to the
   :class:`~xe_forge.lowering.context.ArtifactGuard` and deleted.
3. **Pass 2** (:meth:`VisaCompiler.compile`) recompiles the same SPIR-V with the
   model's ``.visaasm`` placed under the override key. IGC parses and finalizes it
   (register allocation, scheduling, encoding) and emits a zebin carrying the
   stub's ``.ze_info``.

A stock release IGC ignores ``ShaderOverride`` without saying so. Pass 2
therefore requires IGC's own ``OVERRIDEN:`` confirmation. Without it the result
is an infrastructure failure, never a silently-run stub.
``finalizer_igc`` points at an IGC built so that the flag is honoured (see
``docs/VISA_LOWERING.md``).
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from xe_forge.lowering.context import ArtifactGuard
from xe_forge.lowering.triton_analyzer import LaunchRecord
from xe_forge.lowering.visa.diagnostics import CompileResult, sanitize
from xe_forge.lowering.visa.launch import LaunchConfig

STUB_SENTINEL = -1234567  # a runtime value no launch passes; the stub's body never runs

def stub_source(record: LaunchRecord, config: LaunchConfig | None = None) -> str:
    """Triton source of the ABI stub for one captured launch.

    Same name, same parameters in the same order, same constexpr annotations.
    Scalars are never specialized, so one binary serves every runtime value.
    The body asks for program ids and per-work-item local ids, so the runtime
    delivers them, and stores zero to each pointer under a runtime condition no
    launch meets, so no argument is optimized away.
    """
    params = []
    scalars = []
    pointers = []
    for a in record.args:
        if a.kind == "constexpr":
            params.append(f"{a.name}: tl.constexpr")
        else:
            params.append(a.name)
            (pointers if a.kind == "pointer" else scalars).append(a.name)
    dns = f"do_not_specialize={scalars!r}, " if scalars else ""
    # A range wider than the work-group is spread over every work-item, which
    # makes the runtime deliver per-work-item local ids; a narrower one is
    # replicated per sub-group and needs only the lane index.
    nw = config.num_warps if config else record.num_warps
    tpw = config.threads_per_warp if config else record.threads_per_warp
    width = 2 * nw * tpw
    body = [
        "    _xf_pid = tl.program_id(0) + tl.program_id(1) + tl.program_id(2)",
        f"    _xf_lane = tl.arange(0, {width})",
        f"    if {_stub_guard(record, scalars, pointers)}:",
    ]
    body += [f"        tl.store({p} + _xf_pid + _xf_lane, 0)" for p in pointers] or ["        pass"]
    if config is not None and config.slm_bytes and pointers and nw > 1:
        # A reduction across sub-groups makes Triton pass a shared-local-memory argument
        # and IGC enable barriers; its size is set at launch from the kernel's request.
        p0 = pointers[0]
        body += [f"        _xf_s = tl.sum(tl.load({p0} + _xf_lane).to(tl.float32), axis=0)",
                 f"        tl.store({p0} + _xf_pid, _xf_s)"]
    return (
        "# ABI stub generated by xe_forge.lowering.visa.compiler -- inert by construction.\n"
        "import triton\nimport triton.language as tl\n\n\n"
        f"@triton.jit({dns}do_not_specialize_on_alignment={scalars + pointers!r})\n"
        f"def {record.kernel}({', '.join(params)}):\n" + "\n".join(body) + "\n"
    )


def _stub_guard(record: LaunchRecord, scalars: list[str], pointers: list[str]) -> str:
    """A condition the compiler cannot fold away, false for every real launch.

    It must depend on a runtime value: a compiler that knows the range of a
    program id deletes a branch on an impossible one, and the payload with it.
    """
    kinds = {a.name: a.dtype for a in record.args}
    for name in scalars:
        if kinds[name].startswith(("i", "u")) and kinds[name] != "i1":
            return f"{name} == {STUB_SENTINEL}"
        if kinds[name].startswith(("fp", "bf")):
            return f"{name} == {float(STUB_SENTINEL)}"
    if pointers:
        return f"tl.load({pointers[0]}).to(tl.int32) == {STUB_SENTINEL}"
    return "False"


@dataclass
class AbiBuild:
    """The ABI stub for one launch configuration, compiled once.

    Only raw compiler facts are kept: the override key, the stub's ``.ze_info`` and
    its ``.input`` / ``.kernel_attr`` lines. Interpreting them is the model's job
    (``abi-probe`` shows them); nothing here derives a payload layout.
    """

    spv_path: Path
    override_key: str
    zeinfo: dict
    workdir: Path
    stub_header: list[str] = field(default_factory=list)


@dataclass
class VisaBuild:
    result: CompileResult
    zebin: bytes | None = None
    diagnostics_raw: str = ""
    native_asm: str | None = None
    artifacts: dict[str, str] = field(default_factory=dict)


class FinalizerUnavailable(RuntimeError):
    """The configured IGC cannot finalize a .visaasm (missing, or ignores ShaderOverride)."""


class VisaCompiler:
    """Two-pass ocloc driver around IGC's ShaderOverride."""

    def __init__(
        self,
        device: str = "bmg",
        finalizer_igc: str | None = None,
        ocloc: str = "ocloc",
        timeout_s: float = 120,
        extra_options: str = "",
    ):
        self.device = device
        self.finalizer_igc = finalizer_igc
        self.ocloc = ocloc
        self.timeout_s = timeout_s
        self.extra_options = extra_options

    # -- environment --------------------------------------------------------

    def _env(self) -> dict[str, str]:
        env = dict(os.environ)
        # Never inherit IGC dump or override settings from the caller.
        for key in list(env):
            if key.startswith("IGC_"):
                del env[key]
        if self.finalizer_igc:
            lib = Path(self.finalizer_igc) / "lib64"
            if not (lib / "libigc.so.2").exists() and not (lib / "libigc.so").exists():
                raise FinalizerUnavailable(f"no libigc under {lib}")
            env["LD_LIBRARY_PATH"] = f"{lib}:{env.get('LD_LIBRARY_PATH', '')}"
        return env

    def _ocloc(self, spv: Path, out: Path, igc_opts: str) -> subprocess.CompletedProcess:
        options = f"{self.extra_options} -igc_opts '{igc_opts}'".strip()
        cmd = [self.ocloc, "compile", "-file", str(spv), "-spirv_input", "-device", self.device,
               "-o", str(out), "-options", options]
        return subprocess.run(cmd, capture_output=True, text=True, env=self._env(), timeout=self.timeout_s)

    # -- pass 1 -------------------------------------------------------------

    def discover_abi(self, spv_path: Path, entry: str, guard: ArtifactGuard | None = None) -> AbiBuild:
        workdir = Path(tempfile.mkdtemp(prefix="xf_visa_abi_"))
        dump = workdir / "dump"
        dump.mkdir()
        spv = workdir / "stub.spv"
        shutil.copy(spv_path, spv)
        proc = self._ocloc(spv, workdir / "stub.bin", f"ShaderDumpEnable=1,DumpToCustomDir={dump}/")
        if proc.returncode != 0:
            raise RuntimeError(f"ABI stub failed to compile:\n{proc.stdout}\n{proc.stderr}")
        visa_dumps = sorted(dump.glob("*.visaasm"))
        zeinfo_files = sorted(dump.glob("*.zeinfo"))
        if len(visa_dumps) != 1 or len(zeinfo_files) != 1:
            raise RuntimeError(f"expected one stub kernel dump, found {[p.name for p in visa_dumps]}")
        key = visa_dumps[0].name
        stub_visa = visa_dumps[0].read_text()
        zeinfo = yaml.safe_load(zeinfo_files[0].read_text())
        header = [ln.strip() for ln in stub_visa.splitlines() if ln.startswith((".input", ".kernel_attr"))]
        if guard is not None:
            guard.add_tree(dump)
        shutil.rmtree(dump)
        return AbiBuild(spv_path=spv, override_key=key, zeinfo=zeinfo, workdir=workdir, stub_header=header)

    # -- pass 2 -------------------------------------------------------------

    def compile(self, visa_text: str, abi_build: AbiBuild, *, keep_dir: Path | None = None) -> VisaBuild:
        work = Path(tempfile.mkdtemp(prefix="xf_visa_build_"))
        try:
            override = work / "override"
            override.mkdir()
            (override / abi_build.override_key).write_text(visa_text)
            out = work / "kernel.bin"
            t0 = time.perf_counter()
            try:
                proc = self._ocloc(
                    abi_build.spv_path, out, f"ShaderOverride=1,ShaderOverrideFromDir={override}/"
                )
            except subprocess.TimeoutExpired:
                return VisaBuild(CompileResult(False, error=f"finalizer did not finish in {self.timeout_s}s"))
            elapsed = time.perf_counter() - t0
            raw = (proc.stdout or "") + (proc.stderr or "")
            log = override / "OverrideLog.txt"
            applied = "OVERRIDEN:" in raw or (log.exists() and "OVERRIDEN" in log.read_text())
            produced = out.exists() and out.stat().st_size > 0
            if proc.returncode != 0 or not produced:
                error = sanitize(raw) or f"finalizer exited with code {proc.returncode}"
                if proc.returncode is not None and proc.returncode < 0:
                    error += f"\n(the finalizer was killed by signal {-proc.returncode}; the vISA likely broke an invariant it does not check gracefully)"
                return VisaBuild(CompileResult(False, error=error, override_applied=applied, compile_s=elapsed), diagnostics_raw=raw)
            if not applied:
                raise FinalizerUnavailable(
                    "IGC compiled the stub but did not apply the .visaasm override (no 'OVERRIDEN:' "
                    "confirmation). A release IGC ignores ShaderOverride; set LOWER_FINALIZER_IGC to an "
                    "IGC that honours it."
                )
            # A parse error still leaves a (kernel-less) binary behind and exit code 0;
            # the finalizer IGC reports it on stderr with the offending line number.
            parse_errors = parse_error_messages(raw, visa_text)
            info = zebin_info(out)
            if parse_errors or not info.get("text_size"):
                error = parse_errors or (sanitize(raw) + "\nthe finalizer produced no kernel code")
                return VisaBuild(CompileResult(False, error=error, override_applied=True, compile_s=elapsed), diagnostics_raw=raw)
            zebin = out.read_bytes()
            result = CompileResult(
                True,
                override_applied=True,
                simd_size=info.get("simd_size"),
                grf_count=info.get("grf_count"),
                spill_size=info.get("spill_size", 0),
                private_size=info.get("private_size", 0),
                binary_size=info.get("text_size"),
                compile_s=elapsed,
            )
            warnings = sanitize(raw)
            build = VisaBuild(result, zebin=zebin, diagnostics_raw=raw)
            if warnings:
                build.artifacts["finalizer_messages"] = warnings
            build.native_asm = disassemble(out)
            if keep_dir is not None:
                keep_dir.mkdir(parents=True, exist_ok=True)
                shutil.copy(out, keep_dir / "kernel.zebin")
                if build.native_asm:
                    (keep_dir / "kernel.native.asm").write_text(build.native_asm)
            return build
        finally:
            shutil.rmtree(work, ignore_errors=True)


_PARSE_ERROR_RE = re.compile(r"\[vISA override parse error\]\s*(.*)")
_LINE_RE = re.compile(r"near line (\d+)")


def parse_error_messages(raw: str, visa_text: str) -> str:
    """The parser's messages, each followed by the line of the model's file it names."""
    lines = visa_text.splitlines()
    messages = []
    for m in _PARSE_ERROR_RE.finditer(raw):
        msg = m.group(1).strip()
        ln = _LINE_RE.search(msg)
        if ln and 0 < int(ln.group(1)) <= len(lines):
            msg += f"\n  line {ln.group(1)}: {lines[int(ln.group(1)) - 1].strip()}"
        messages.append(msg)
    return "\n".join(messages)


_INPUT_RE = re.compile(r"^\s*\.input\s+\S+\s+offset=(\d+)\s+size=(\d+)", re.MULTILINE)


def input_layout(text: str) -> list[tuple[int, int]]:
    """(offset, size) of every ``.input`` line, sorted."""
    return sorted((int(o), int(z)) for o, z in _INPUT_RE.findall(text))


def input_mismatch(visa_text: str, abi_build: AbiBuild) -> str:
    """Empty if the kernel binds exactly the payload slots the runtime fills."""
    want = input_layout("\n".join(abi_build.stub_header))
    got = input_layout(visa_text)
    if got == want:
        return ""
    missing = sorted(set(want) - set(got))
    extra = sorted(set(got) - set(want))
    return (
        "the .input declarations do not match the payload for this launch configuration "
        f"(run ./abi-probe with the same configuration). Missing (offset, size): {missing}; "
        f"not in the payload: {extra}"
    )


def probe_report(abi_build: AbiBuild, record: LaunchRecord, config: LaunchConfig) -> str:
    """Raw ABI facts for a configuration, as ``abi-probe`` prints them."""
    k = next(k for k in abi_build.zeinfo["kernels"] if k["name"] == record.kernel)
    env = k.get("execution_env", {})
    runtime = [a for a in record.args if a.kind != "constexpr"]
    doc = {
        "launch_config": {"num_warps": config.num_warps, "threads_per_warp": config.threads_per_warp,
                          "slm_bytes": config.slm_bytes},
        "kernel_parameters": [{"index": i, "name": a.name, "kind": a.kind, "dtype": a.dtype}
                              for i, a in enumerate(runtime)],
        "ze_info": {
            "execution_env": {key: env[key] for key in sorted(env)},
            "per_thread_payload_arguments": k.get("per_thread_payload_arguments", []),
            "payload_arguments": k.get("payload_arguments", []),
        },
        "stub_header": abi_build.stub_header,
    }
    return yaml.safe_dump(doc, sort_keys=False, width=110)


def zebin_info(path: Path) -> dict:
    """SIMD, GRF, spill and code size of the kernel in a zebin."""
    from elftools.elf.elffile import ELFFile

    info: dict = {}
    with open(path, "rb") as f:
        elf = ELFFile(f)
        ze = elf.get_section_by_name(".ze_info")
        if ze is not None:
            doc = yaml.safe_load(ze.data().decode())
            env = doc["kernels"][0]["execution_env"]
            info["simd_size"] = env.get("simd_size")
            info["grf_count"] = env.get("grf_count")
            info["spill_size"] = env.get("spill_size", 0)
            info["private_size"] = env.get("private_size", 0)
        text = [s for s in elf.iter_sections() if s.name.startswith(".text.")]
        if text:
            info["text_size"] = sum(s.data_size for s in text)
    return info


def disassemble(path: Path, platform: str = "xe2") -> str | None:
    """Native ISA of a zebin via iga64, for the run record (not shown to the model)."""
    iga = shutil.which("iga64")
    if iga is None:
        return None
    from elftools.elf.elffile import ELFFile

    with open(path, "rb") as f:
        text = [s.data() for s in ELFFile(f).iter_sections() if s.name.startswith(".text.")]
    if not text:
        return None
    with tempfile.NamedTemporaryFile(suffix=".bin") as tmp:
        tmp.write(text[0])
        tmp.flush()
        proc = subprocess.run([iga, "-d", f"-p={platform}", tmp.name], capture_output=True, text=True, timeout=60)
    return proc.stdout if proc.returncode == 0 else None
